from typing import List, Optional, Literal
from pydantic import BaseModel, Field


class Message(BaseModel):
    """
    Schema representing a single message within the conversation flow.
    """
    role: Literal["system", "user", "assistant"] = Field(
        ...,
        description="The role of the message sender. Allowed values are 'system', 'user', or 'assistant'."
    )
    content: str = Field(
        ...,
        min_length=1,
        description="The body content of the message."
    )


class ChatRequest(BaseModel):
    """
    Schema for validating requests sent to the chat completion endpoint.
    """
    messages: List[Message] = Field(
        ...,
        min_length=1,
        description="A list of messages forming the conversation thread. Last message should normally be from the user."
    )
    temperature: float = Field(
        default=0.7,
        ge=0.0,
        le=2.0,
        description="Controls the randomness of the model response (0.0 is deterministic, higher values are more creative)."
    )
    max_tokens: Optional[int] = Field(
        default=None,
        gt=0,
        description="Maximum number of tokens that the model can generate in the response."
    )


class UsageInfo(BaseModel):
    """
    Token usage metrics to help monitor and manage rate limits.
    """
    prompt_tokens: int = Field(..., description="Tokens consumed by the prompt.")
    completion_tokens: int = Field(..., description="Tokens generated by the model response.")
    total_tokens: int = Field(..., description="Total tokens used (prompt + completion).")


class ChatResponse(BaseModel):
    """
    Schema for structuring responses returned from the chat completion endpoint.
    """
    response: str = Field(
        ...,
        description="The message generated by the language model."
    )
    model: str = Field(
        ...,
        description="The name of the Groq model utilized for completion."
    )
    usage: Optional[UsageInfo] = Field(
        default=None,
        description="Detailed token usage metrics for the request."
    )

