from typing import List
from pydantic import BaseModel, Field


class SalesItem(BaseModel):
    product: str = Field(..., description="Name of the product")
    qty: float = Field(..., description="Quantity of the product sold")
    revenue: float = Field(..., description="Total revenue generated by the product")


class StockItem(BaseModel):
    product: str = Field(..., description="Name of the product")
    remaining: float = Field(..., description="Remaining quantity in stock")


class InsightRequest(BaseModel):
    shop_name: str = Field(..., description="Name of the shop")
    period: str = Field(..., description="Sales and stock time period, e.g., 'last_30_days'")
    sales: List[SalesItem] = Field(..., description="List of products sold and their sales figures")
    stock: List[StockItem] = Field(..., description="List of products and their current stock levels")


class AnalyticsSummary(BaseModel):
    total_revenue: float = Field(..., description="Total revenue generated across all products")
    top_product: str = Field(..., description="Name of the top-selling product by quantity sold")
    low_stock: List[str] = Field(..., description="List of product names with stock level below 10 units")


class InsightResponse(BaseModel):
    success: bool = Field(..., description="Status of the API request")
    analytics: AnalyticsSummary = Field(..., description="Python-computed business analytics summary")
    ai_insight_bn: str = Field(..., description="AI-generated business insights in Bengali")
    model: str = Field(..., description="Name of the LLM model utilized for insights")
