from typing import List, Optional
from pydantic import BaseModel, Field


class SalesItem(BaseModel):
    product: str = Field(default="", description="Name of the product")
    qty: Optional[float] = Field(default=0.0, description="Quantity of the product sold")
    revenue: Optional[float] = Field(default=0.0, description="Total revenue generated by the product")
    date: Optional[str] = Field(default=None, description="ISO Date string of the sale transaction")


class StockItem(BaseModel):
    product: str = Field(default="", description="Name of the product")
    remaining: Optional[float] = Field(default=0.0, description="Remaining quantity in stock")
    buy_price: Optional[float] = Field(default=0.0, description="Buying cost price per unit")
    sell_price: Optional[float] = Field(default=0.0, description="Selling retail price per unit")


class InsightRequest(BaseModel):
    shop_name: Optional[str] = Field(default="আমার জেনারেল স্টোর", description="Name of the shop")
    period: Optional[str] = Field(default="last_30_days", description="Sales and stock time period, e.g., 'last_30_days'")
    sales: Optional[List[SalesItem]] = Field(default_factory=list, description="List of products sold and their sales figures")
    stock: Optional[List[StockItem]] = Field(default_factory=list, description="List of products and their current stock levels")
    customer_baki: Optional[float] = Field(default=0.0, description="Total outstanding customer due balances (receivables)")
    supplier_baki: Optional[float] = Field(default=0.0, description="Total outstanding supplier due balances (payables)")


class AnalyticsSummary(BaseModel):
    total_revenue: float = Field(..., description="Total revenue generated across all products")
    inventory_value: float = Field(..., description="Total buying cost value of remaining inventory")
    dead_stock_value: float = Field(..., description="Cost value of capital locked in dead stock")
    revenue_growth: float = Field(..., description="Growth/decline percentage comparing current vs previous sub-periods")
    top_product: str = Field(..., description="Name of the top-selling product by quantity sold")
    stockout_predictions: List[str] = Field(default_factory=list, description="Alert list of products expected to run out soon and estimated days remaining")
    sales_velocity_alerts: List[str] = Field(default_factory=list, description="Fastest moving products with high demand run-rates")
    customer_baki: float = Field(default=0.0, description="Transmitted customer due receivables")
    supplier_baki: float = Field(default=0.0, description="Transmitted supplier due payables")


class InsightResponse(BaseModel):
    success: bool = Field(..., description="Status of the API request")
    analytics: AnalyticsSummary = Field(..., description="Advanced retail analytics summary computed locally")
    ai_insight_bn: str = Field(..., description="AI-generated business insights in Bengali")
    model: str = Field(..., description="Name of the LLM model utilized for insights")
