from typing import List, Optional
from pydantic import BaseModel, Field


class SalesItem(BaseModel):
    product: str = Field(default="", description="Name of the product")
    qty: Optional[float] = Field(default=0.0, description="Quantity of the product sold")
    revenue: Optional[float] = Field(default=0.0, description="Total revenue generated by the product")


class StockItem(BaseModel):
    product: str = Field(default="", description="Name of the product")
    remaining: Optional[float] = Field(default=0.0, description="Remaining quantity in stock")


class InsightRequest(BaseModel):
    shop_name: Optional[str] = Field(default="আমার জেনারেল স্টোর", description="Name of the shop")
    period: Optional[str] = Field(default="last_30_days", description="Sales and stock time period, e.g., 'last_30_days'")
    sales: Optional[List[SalesItem]] = Field(default_factory=list, description="List of products sold and their sales figures")
    stock: Optional[List[StockItem]] = Field(default_factory=list, description="List of products and their current stock levels")


class AnalyticsSummary(BaseModel):
    total_revenue: float = Field(..., description="Total revenue generated across all products")
    top_product: str = Field(..., description="Name of the top-selling product by quantity sold")
    low_stock: List[str] = Field(..., description="List of product names with stock level below 10 units")


class InsightResponse(BaseModel):
    success: bool = Field(..., description="Status of the API request")
    analytics: AnalyticsSummary = Field(..., description="Python-computed business analytics summary")
    ai_insight_bn: str = Field(..., description="AI-generated business insights in Bengali")
    model: str = Field(..., description="Name of the LLM model utilized for insights")
